name = "dev-notes"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

kv_namespaces = [
  { binding = "notes", id = "bcfa8b926c3c4fbcbbba738931036085", preview_id = "b708ce551f244538986e92b45f0e775a" },
]

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"
